const fs = require('fs');

const ContentJs = {
  getAllContentJs() {
    const readPath = './src/script/content/';
    const writeFileName = './content_script.js';
    fs.readdir(readPath, (err, files) => {
      if (err) {
        console.log(err);
      } else {
        const saveFileName = [];
        files.forEach((filename) => {
          const exp = filename.split('.js');
          if (exp.length >= 2) {
            saveFileName.push(filename);
          }
        });
        const firstLine = `//this is auto generated by [npm run dev/build] command
const nowHost = window.location.host;`;
        fs.writeFileSync(writeFileName, firstLine);
        for (let i = 0; i < saveFileName.length; i += 1) {
          const expUrl = saveFileName[i].split('.js');
          fs.appendFileSync(writeFileName, `
if(nowHost === '${expUrl[0]}'){
`);
          const fileInfo = fs.readFileSync(readPath + saveFileName[i]);
          fs.appendFileSync(writeFileName, String(fileInfo));
          fs.appendFileSync(writeFileName, `}`);
        }
      }
    });
  },
  generate() {
    this.getAllContentJs();
  },
};
ContentJs.generate();
