//this is auto generated by [npm run dev/build] command
const nowHost = window.location.host;
if(nowHost === 'blog.csdn.net'){
// 设置csdn烦人的【展开阅读全文】、【弹出登录】功能
setTimeout(() => {
  document.getElementById('article_content').style.height = 'auto';
  const hideOpenMore = document.getElementsByClassName('hide-article-box');
  for (let i = 0; i < hideOpenMore.length; i += 1) {
    hideOpenMore[i].remove();
  }
  document.getElementById('passportbox').style.display = 'none';
  const loginMark = document.getElementsByClassName('login-mark');
  for (let i = 0; i < loginMark.length; i += 1) {
    loginMark[i].remove();
  }
}, 2000);
}
if(nowHost === 'www.baidu.com'){
setTimeout(() => {
  // 右侧百度热榜
  const rightObj = document.getElementById('content_right');
  if (rightObj !== undefined) { rightObj.remove(); }
  // 左侧广告
  for (let j = 1; j < 10; j += 1) {
    const tempMin = j * 1000;
    const tempMax = tempMin + 20;
    for (let i = tempMin; i < tempMax; i += 1) {
      const pObj = document.getElementById(`${i}`);
      if (pObj !== undefined && pObj !== null) {
        pObj.style.display = 'none !important';
        pObj.remove();
      }
    }
  }
}, 1000);
setInterval(() => {
  // 左侧广告
  const tuiguangPpm = document.getElementsByClassName('EC_ppim_new_gap_bottom');
  for (let i = 0; i < tuiguangPpm.length; i += 1) {
    tuiguangPpm[i].remove();
  }
  const tuiGuangObj = document.getElementsByClassName('ec_tuiguang_pplink');
  for (let i = 0; i < tuiGuangObj.length; i += 1) {
    tuiGuangObj[i].parentNode.parentNode.remove();
  }
}, 10);
}
if(nowHost === 'www.coder55.com'){
setTimeout(() => {
  document.getElementById('btw-mask').style.display = 'none';
  document.getElementById('btw-modal').style.display = 'none';
}, 1000);
}
if(nowHost === 'yq.aliyun.com'){
setTimeout(() => {
  const hideContent = document.getElementsByClassName('article-hide-content');
  if (hideContent.length > 0) {
    console.log('block hide content');
    console.log(hideContent[0]);
    hideContent[0].style.height = 'auto';
    hideContent[0].style.overflow = 'visible';
  }
  const mask = document.getElementsByClassName('dbl-popup-backdrop');
  if (mask.length > 0) {
    console.log('block mask');
    mask[0].style.display = 'none';
  }
}, 5000);
}